export const CATEGORY_LABELS = {
  "Başlangıçlar":       { en: "Starters",           tr: "Başlangıçlar" },
  "Tavuk Menüsü":       { en: "Chicken Menu",        tr: "Tavuk Menüsü" },
  "Balık Menüsü":       { en: "Fish Menu",           tr: "Balık Menüsü" },
  "Fix Menü":           { en: "Set Menu",            tr: "Fix Menü" },
  "Et Menüsü":          { en: "Meat Menu",           tr: "Et Menüsü" },
  "Salatalar":          { en: "Salads",              tr: "Salatalar" },
  "Makarnalar":         { en: "Pastas",              tr: "Makarnalar" },
  "Hamburgerler":       { en: "Burgers",             tr: "Hamburgerler" },
  "Pideler":            { en: "Pides",               tr: "Pideler" },
  "Omletler":           { en: "Omelets",             tr: "Omletler" },
  "Tatlılar":           { en: "Desserts",            tr: "Tatlılar" },
  "Alkolsüz İçecekler": { en: "Non-Alcoholic Drinks",tr: "Alkolsüz İçecekler" },
  "Kokteyller":         { en: "Cocktails",           tr: "Kokteyller" },
  "Bira":               { en: "Beer",                tr: "Bira" },
  "Viski Şişe":         { en: "Whiskey Bottle",      tr: "Viski Şişe" },
  "Viski":              { en: "Whiskey",             tr: "Viski" },
  "Rakı":               { en: "Rakı",                tr: "Rakı" },
  "Şarap":              { en: "Wine",                tr: "Şarap" },
  "Sıcak İçecekler":    { en: "Hot Drinks",          tr: "Sıcak İçecekler" },
  "The Finger Foods":   { en: "Finger Foods",        tr: "Atıştırmalıklar" },
}
